baseURL = "http://joemiller.me"
languageCode = "en-us"
title = "Joe Miller"
theme = "m10c"
enableRobotsTXT = true

# Google Analytics UA number
googleAnalytics = "UA-17214890-1"

pygmentsUseClasses = true
#pygmentsUseClassic = true
#pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[permalinks]
  post = "/:year/:month/:title/"

[params]
  author = "Joe Miller"
  description = "Infrastructure Ops/Engineering. Continuously DevOping at Webscale"

  # path is relative to ./static/
  avatar = "avatar.jpg"

  [[params.social]]
    name = "github"
    url = "https://github.com/joemiller"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/miller_joe"

  [[params.social]]
    name = "key"
    url = "https://keybase.io/joemiller"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#d5d9e6"
    lightestColor = "#eeeef6"
    primaryColor = "#e8a20c"